---
resource_types:
  - name: rubygems
    type: docker-image
    source:
      repository: govuk/concourse-rubygems
      tag: 0.0.3

resources:
- icon: github-circle
  name: govuk-connect
  source:
    uri: https://github.com/alphagov/govuk-connect
  type: git
- name: rubygems
  type: rubygems
  source:
    gem_name: govuk-connect
    credentials: |
      :rubygems_api_key: ((rubygems_api_key))

jobs:
- name: update-pipeline
  plan:
    - get: govuk-connect
      trigger: true
    - set_pipeline: govuk-connect
      file: govuk-connect/concourse.yml
- name: release-gem
  plan:
  - get: govuk-connect
    trigger: true
  - task: build-gem
    config:
      container_limits: {}
      image_resource:
        source:
          repository: ruby
          tag: 2.6
          username: ((docker_hub_username))
          password: ((docker_hub_authtoken))
        type: registry-image
      inputs:
      - name: govuk-connect
      outputs:
      - name: gems
        path: dist
      platform: linux
      run:
        args:
        - -c
        - |
          echo "=== Building Gem..."
          cd govuk-connect
          mkdir dist
          gem build govuk-connect.gemspec --output dist/release.gem
        path: /bin/bash
  - put: rubygems
    params:
      gem_dir: dist
      gem_regex: govuk-connect
    get_params:
      skip_download: true
